# Generated by Django 4.0.2 on 2022-02-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='meeting_id',
        ),
    ]
