# Generated by Django 4.0.2 on 2022-02-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zoom_access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zoom_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
